//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppObject
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string TableName { get; set; }
        public bool IsOnMenu { get; set; }
        public bool IsSortable { get; set; }
        public bool IsPublishable { get; set; }
        public Nullable<bool> IsFilterable { get; set; }
        public Nullable<int> PageSize { get; set; }
        public Nullable<int> Priority { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public long CreateUserID { get; set; }
        public long UpdateUserID { get; set; }
    }
}
