//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Article_Comment = new HashSet<Article_Comment>();
            this.Article_Like = new HashSet<Article_Like>();
            this.Article_Share = new HashSet<Article_Share>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public long TopicID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Img_src { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string CreateUserID { get; set; }
        public string UpdateUserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Comment> Article_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Like> Article_Like { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Share> Article_Share { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
