//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public long ID { get; set; }
        public long DoctorSpecialyID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string EmailAddress { get; set; }
        public string Website { get; set; }
        public string ClinicPhone { get; set; }
        public string Mobile { get; set; }
        public long CountryID { get; set; }
        public long CityID { get; set; }
        public string Village { get; set; }
        public string StreetNumName { get; set; }
        public string StreetLine1 { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Lattitude { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public long CreateUserID { get; set; }
        public Nullable<long> UpdateUserID { get; set; }
    
        public virtual DoctorSpecialty DoctorSpecialty { get; set; }
    }
}
