//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthDiary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthDiary()
        {
            this.HealthDiaryAttachments = new HashSet<HealthDiaryAttachment>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public Nullable<long> FamilyMemberID { get; set; }
        public string Description { get; set; }
        public Nullable<long> HealthDiaryTypeID { get; set; }
        public Nullable<int> Priority { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string CreateUserID { get; set; }
        public string UpdateUserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual HealthDiaryType HealthDiaryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthDiaryAttachment> HealthDiaryAttachments { get; set; }
    }
}
