//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthDiaryAttachment
    {
        public long ID { get; set; }
        public long HealthDiaryID { get; set; }
        public string File_src { get; set; }
        public string FileType { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual HealthDiary HealthDiary { get; set; }
    }
}
