//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public long ID { get; set; }
        public long LabelGroupID { get; set; }
        public string Label1 { get; set; }
        public Nullable<long> LanguageID { get; set; }
    
        public virtual LabelGroup LabelGroup { get; set; }
        public virtual Language Language { get; set; }
    }
}
