//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long ID { get; set; }
        public System.Guid UserID { get; set; }
        public long ObjectID { get; set; }
        public Nullable<long> RecordID { get; set; }
        public Nullable<long> TransactionTypeID { get; set; }
        public string Metadata { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTransaction { get; set; }
    
        public virtual TransactionType TransactionType { get; set; }
    }
}
