//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalReminder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalReminder()
        {
            this.MedicalRemiderDateTimes = new HashSet<MedicalRemiderDateTime>();
            this.MedicalReminderAttachments = new HashSet<MedicalReminderAttachment>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public Nullable<long> FamilyMemberID { get; set; }
        public string MedicineName { get; set; }
        public Nullable<int> QtyDoze { get; set; }
        public Nullable<long> MedicineUnitID { get; set; }
        public bool IsEveryday { get; set; }
        public bool IsLifetime { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string CreateUserID { get; set; }
        public string UpdateUserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalRemiderDateTime> MedicalRemiderDateTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalReminderAttachment> MedicalReminderAttachments { get; set; }
    }
}
