//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NurseNovaEntities : DbContext
    {
        public NurseNovaEntities()
            : base("name=NurseNovaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<AppObject> AppObjects { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Article_Comment> Article_Comment { get; set; }
        public virtual DbSet<Article_Like> Article_Like { get; set; }
        public virtual DbSet<Article_Share> Article_Share { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorSpecialty> DoctorSpecialties { get; set; }
        public virtual DbSet<FamilyMember> FamilyMembers { get; set; }
        public virtual DbSet<FavoriteArticle> FavoriteArticles { get; set; }
        public virtual DbSet<FavoriteDoctor> FavoriteDoctors { get; set; }
        public virtual DbSet<HealthDiary> HealthDiaries { get; set; }
        public virtual DbSet<HealthDiaryAttachment> HealthDiaryAttachments { get; set; }
        public virtual DbSet<HealthDiaryType> HealthDiaryTypes { get; set; }
        public virtual DbSet<Label> Labels { get; set; }
        public virtual DbSet<LabelGroup> LabelGroups { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MedicalProfile> MedicalProfiles { get; set; }
        public virtual DbSet<MedicalRecord> MedicalRecords { get; set; }
        public virtual DbSet<MedicalRecordAttachment> MedicalRecordAttachments { get; set; }
        public virtual DbSet<MedicalRecordType> MedicalRecordTypes { get; set; }
        public virtual DbSet<MedicalRemiderDateTime> MedicalRemiderDateTimes { get; set; }
        public virtual DbSet<MedicalReminder> MedicalReminders { get; set; }
        public virtual DbSet<MedicalReminderAttachment> MedicalReminderAttachments { get; set; }
        public virtual DbSet<MyVaccination> MyVaccinations { get; set; }
        public virtual DbSet<RefreshToken> RefreshTokens { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<SeededData> SeededDatas { get; set; }
        public virtual DbSet<SeededDataGroup> SeededDataGroups { get; set; }
        public virtual DbSet<StandardVaccination> StandardVaccinations { get; set; }
        public virtual DbSet<StandardVaccinationCategory> StandardVaccinationCategories { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
    }
}
